[project]
name = 'Tokenized-Workforce-Skills-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experience-validation]
path = 'contracts/experience-validation.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.skill-certification]
path = 'contracts/skill-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.training-verification]
path = 'contracts/training-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
